/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedFormelsammlungRouteImport } from './routes/_authenticated/formelsammlung'
import { Route as AuthenticatedFortschrittRouteImport } from './routes/_authenticated/fortschritt'
import { Route as AuthenticatedLernblaetterRouteImport } from './routes/_authenticated/lernblaetter'
import { Route as AuthenticatedProbepruefungenRouteImport } from './routes/_authenticated/probepruefungen'
import { Route as AuthenticatedRechnenRouteImport } from './routes/_authenticated/rechnen'
import { Route as AuthenticatedTagesplanRouteImport } from './routes/_authenticated/tagesplan'
import { Route as AuthenticatedWissenskartenRouteImport } from './routes/_authenticated/wissenskarten'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFormelsammlungRoute =
  AuthenticatedFormelsammlungRouteImport.update({
    id: '/formelsammlung',
    path: '/formelsammlung',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFortschrittRoute =
  AuthenticatedFortschrittRouteImport.update({
    id: '/fortschritt',
    path: '/fortschritt',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLernblaetterRoute =
  AuthenticatedLernblaetterRouteImport.update({
    id: '/lernblaetter',
    path: '/lernblaetter',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProbepruefungenRoute =
  AuthenticatedProbepruefungenRouteImport.update({
    id: '/probepruefungen',
    path: '/probepruefungen',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRechnenRoute = AuthenticatedRechnenRouteImport.update({
  id: '/rechnen',
  path: '/rechnen',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTagesplanRoute = AuthenticatedTagesplanRouteImport.update({
  id: '/tagesplan',
  path: '/tagesplan',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWissenskartenRoute =
  AuthenticatedWissenskartenRouteImport.update({
    id: '/wissenskarten',
    path: '/wissenskarten',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/formelsammlung': typeof AuthenticatedFormelsammlungRoute
  '/fortschritt': typeof AuthenticatedFortschrittRoute
  '/lernblaetter': typeof AuthenticatedLernblaetterRoute
  '/probepruefungen': typeof AuthenticatedProbepruefungenRoute
  '/rechnen': typeof AuthenticatedRechnenRoute
  '/tagesplan': typeof AuthenticatedTagesplanRoute
  '/wissenskarten': typeof AuthenticatedWissenskartenRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/formelsammlung': typeof AuthenticatedFormelsammlungRoute
  '/fortschritt': typeof AuthenticatedFortschrittRoute
  '/lernblaetter': typeof AuthenticatedLernblaetterRoute
  '/probepruefungen': typeof AuthenticatedProbepruefungenRoute
  '/rechnen': typeof AuthenticatedRechnenRoute
  '/tagesplan': typeof AuthenticatedTagesplanRoute
  '/wissenskarten': typeof AuthenticatedWissenskartenRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/formelsammlung': typeof AuthenticatedFormelsammlungRoute
  '/_authenticated/fortschritt': typeof AuthenticatedFortschrittRoute
  '/_authenticated/lernblaetter': typeof AuthenticatedLernblaetterRoute
  '/_authenticated/probepruefungen': typeof AuthenticatedProbepruefungenRoute
  '/_authenticated/rechnen': typeof AuthenticatedRechnenRoute
  '/_authenticated/tagesplan': typeof AuthenticatedTagesplanRoute
  '/_authenticated/wissenskarten': typeof AuthenticatedWissenskartenRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/formelsammlung'
    | '/fortschritt'
    | '/lernblaetter'
    | '/probepruefungen'
    | '/rechnen'
    | '/tagesplan'
    | '/wissenskarten'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/formelsammlung'
    | '/fortschritt'
    | '/lernblaetter'
    | '/probepruefungen'
    | '/rechnen'
    | '/tagesplan'
    | '/wissenskarten'
    | '/'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/formelsammlung'
    | '/_authenticated/fortschritt'
    | '/_authenticated/lernblaetter'
    | '/_authenticated/probepruefungen'
    | '/_authenticated/rechnen'
    | '/_authenticated/tagesplan'
    | '/_authenticated/wissenskarten'
    | '/_authenticated/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/formelsammlung': {
      id: '/_authenticated/formelsammlung'
      path: '/formelsammlung'
      fullPath: '/formelsammlung'
      preLoaderRoute: typeof AuthenticatedFormelsammlungRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fortschritt': {
      id: '/_authenticated/fortschritt'
      path: '/fortschritt'
      fullPath: '/fortschritt'
      preLoaderRoute: typeof AuthenticatedFortschrittRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lernblaetter': {
      id: '/_authenticated/lernblaetter'
      path: '/lernblaetter'
      fullPath: '/lernblaetter'
      preLoaderRoute: typeof AuthenticatedLernblaetterRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/probepruefungen': {
      id: '/_authenticated/probepruefungen'
      path: '/probepruefungen'
      fullPath: '/probepruefungen'
      preLoaderRoute: typeof AuthenticatedProbepruefungenRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rechnen': {
      id: '/_authenticated/rechnen'
      path: '/rechnen'
      fullPath: '/rechnen'
      preLoaderRoute: typeof AuthenticatedRechnenRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tagesplan': {
      id: '/_authenticated/tagesplan'
      path: '/tagesplan'
      fullPath: '/tagesplan'
      preLoaderRoute: typeof AuthenticatedTagesplanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/wissenskarten': {
      id: '/_authenticated/wissenskarten'
      path: '/wissenskarten'
      fullPath: '/wissenskarten'
      preLoaderRoute: typeof AuthenticatedWissenskartenRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedFormelsammlungRoute: typeof AuthenticatedFormelsammlungRoute
  AuthenticatedFortschrittRoute: typeof AuthenticatedFortschrittRoute
  AuthenticatedLernblaetterRoute: typeof AuthenticatedLernblaetterRoute
  AuthenticatedProbepruefungenRoute: typeof AuthenticatedProbepruefungenRoute
  AuthenticatedRechnenRoute: typeof AuthenticatedRechnenRoute
  AuthenticatedTagesplanRoute: typeof AuthenticatedTagesplanRoute
  AuthenticatedWissenskartenRoute: typeof AuthenticatedWissenskartenRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedFormelsammlungRoute: AuthenticatedFormelsammlungRoute,
  AuthenticatedFortschrittRoute: AuthenticatedFortschrittRoute,
  AuthenticatedLernblaetterRoute: AuthenticatedLernblaetterRoute,
  AuthenticatedProbepruefungenRoute: AuthenticatedProbepruefungenRoute,
  AuthenticatedRechnenRoute: AuthenticatedRechnenRoute,
  AuthenticatedTagesplanRoute: AuthenticatedTagesplanRoute,
  AuthenticatedWissenskartenRoute: AuthenticatedWissenskartenRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
